### ISSUE TITLE
Allow custom tag color

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [MemeLabs/chat-gui#124]
could work like this 
`/tag Dashh #a83269`

maybe the ability to save custom colors too?
`/tag Dashh #a83269 darkpink`

Any objections?

**Comment by xDashh** [comment]
You'd have to build in backwards compatibility, or some converter, and be really sure to not mess up people's settings. But otherwise giving some pre-defined names (red,green,blue,...) which are translated to colors-codes, but also allowing color-codes themselves seems like the best solution.
Also print a text informing about this (existence of colors and codes) when a user gives an invalid input instead of choosing something randomly.

Sounds good?

**Comment by jbpratt78** [comment]
I don't see the need to save colors, though if someone wanted to utilize a name http://chir.ag/projects/name-that-color/#6195ED something like this may work. Although, in my opinion, this part of it is too 'memey'/ too much effort.

Very much in favor of custom colors though.

**Comment by SoMuchForSubtlety** [comment]
yea of course the current colors need to be unaffected (maybe even un-reassignable?)

I agree that assigning names to colors is a stretch goal, but I never miss the opportunity to add more complexity and bugs ;)

**Comment by jbpratt78** [comment]
Closed with a71aa925f
