### ISSUE TITLE
fix caching

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#42]
Reminder issue that despite all efforts so far, Chrome still caches parts of the page when an update is deployed. Figure out if we actually need to set an explicit do-not-cache header for it to be happy.

If that does it, consider rolling back the fix that changes file-names on every update (not sure if that would still have any purpose, but also not sure if it has any downsides)

**Comment by JoannesJ** [comment]
The fingerprinting has to stay, otherwise the assets referred to by the html document would still come from the cache, being static addresses.

The fingerprinting is doing it's thing, it's just that what I've read said that html documents where always checked on the server, but apparently there are still exceptions.
The only de-synchronization we should be seeing now is between the html document and the assets it requires.

**Comment by xDashh** [comment]
User feedback shows that we are mostly fine now. A "normal" f5 refresh seems to fix everything on chrome. Something like this might "fix" that too: https://stackoverflow.com/questions/25661538/what-to-do-with-nginx-cache-for-html-files

**Comment by xDashh** [comment]
We settled on no-caching the whole chat domain for now. That should definitely solve this, although maybe not in an ideal way. New config will be in an upcoming commit.
