### ISSUE TITLE
Change the autocomplete weight change trigger

### ISSUE THREAD

**Issue by Efulefu** [MemeLabs/chat-gui#53]
I've seen complaints about the fact that now an autocomplete token weight is updated upon finishing tabbing to it.

This means that you can for example tab to someone, realize you 'mis-tabbed', backspace and correct it without tabbing but you'll still get the wrong person prioritized afterwards.

The change I'd like to suggest is as one of the last steps before sending the message, do a split(' '), check for tokens and update if found. We would however still want to keep the update of the weight on finishing tabbing, if you want to spam an emote or someone's name?

Also a question would be then whether to check for tokens before or after validating the message for size/whatever other client-side validation is being done atm, or maybe even do it after server confirms reception.

**Comment by xDashh** [comment]
Sounds good in principle to me, will have to see how it "feels" as with most of those kinda changes.

Regarding the last part, just do it client-side, since the client does not get told which message any error given by the backend relates to. Also intuitively just because e.g. a message was too long, doesn't mean the tab preference shouldn't be updated.

**Comment by xDashh** [comment]
Implemented in https://github.com/MemeLabs/chat-gui/pull/56.
